#!/usr/bin/env bash

set -e
TASK=$1
ARGS=${@:2}


help__buildNanoMQ="docker build nanomq image"
task_buildNanoMQ() {
  docker build -f Dockerfile.nanomq -t nanomq-image .
}

help__runNanoMQ="docker run nanomq container"
task_runNanoMQ() {
  docker run -d \
    --name nanomq-container \
    -p 1883:1883 \
    -p 8083:8083 \
    -p 8883:8883 \
    --restart always \
    --network="host" \
    nanomq-image
}

help__killNanoMQ="docker kill nanomq container"
task_killNanoMQ() {
  docker kill nanomq-container
  docker rm nanomq-container
}


## main
list_all_helps() {
  compgen -v | egrep "^help__.*"
}

NEW_LINE=$'\n'
if type -t "task_$TASK" &>/dev/null; then
  task_${TASK} ${ARGS}
else
  echo "usage: $0 <task> [<..args>]"
  echo "task:"

  HELPS=""
  for help in $(list_all_helps); do

    HELPS="$HELPS    ${help/help__/} |-- ${!help}$NEW_LINE"
  done

  echo "$HELPS" | column -t -s "|"
  exit 1
fi
