#!/usr/bin/env bash

set -e
TASK=$1
ARGS=${@:2}


help__buildNanoMQ="docker build nanomq image"
task_buildNanoMQ() {
  if sudo docker images --format '{{.Repository}}' | grep -q '^nanomq-image$'; then
    echo "🟡 nanomq-image already exists. Skipping build..."
  else
    sudo docker build -f Dockerfile.nanomq -t nanomq-image .
  fi
}

help__runNanoMQ="docker run nanomq container"
task_runNanoMQ() {
  if sudo docker ps -a --format '{{.Names}}' | grep -q '^nanomq-container$'; then
    echo "🟡 nanomq-container is already running or exists. Skipping..."
  else
    sudo docker run -d \
      --name nanomq-container \
      -p 1883:1883 \
      -p 8083:8083 \
      -p 8883:8883 \
      --restart always \
      --network="host" \
      nanomq-image
  fi
}

help__killNanoMQ="docker kill nanomq container"
task_killNanoMQ() {
  sudo docker kill nanomq-container
  sudo docker rm nanomq-container
}


## main
list_all_helps() {
  compgen -v | egrep "^help__.*"
}

NEW_LINE=$'\n'
if type -t "task_$TASK" &>/dev/null; then
  task_${TASK} ${ARGS}
else
  echo "usage: $0 <task> [<..args>]"
  echo "task:"

  HELPS=""
  for help in $(list_all_helps); do

    HELPS="$HELPS    ${help/help__/} |-- ${!help}$NEW_LINE"
  done

  echo "$HELPS" | column -t -s "|"
  exit 1
fi
